### ISSUE TITLE
SD Card problem 

### ISSUE THREAD

**Issue by ghost** [kiwanowski/diversity#2]
SD Card Not Present  - Error 
I connected it according to the scheme, the problem still did not disappear. 
connected jumpers directly, to check, still the error remains.
SD Card Not Present  - Off Teensy automatically

**Comment by nugravity** [comment]
pin 4 - DC for TFT

**Comment by kiwanowski** [comment]
![Teensy-4 0-Pinout-Top](https://user-images.githubusercontent.com/10254780/171728860-5606bd9c-21d5-4202-b515-0d9ebdfc98f8.jpg)

I mean pin number 4. It should be connected to ground or the sd card detect pin

**Comment by nugravity** [comment]
![Untitled](https://user-images.githubusercontent.com/35999196/171730417-fcb2c2b8-41b7-48b6-b58f-fe742eb06cd0.png)


tell me where to connect? judging by your diagram, 4 pin is a reset for the display

**Comment by nugravity** [comment]
I haven't been able to fix the problem

**Comment by kiwanowski** [comment]
can you provide a photo of the pcb?

**Comment by nugravity** [comment]
![Снимок экрана 2022-06-10 в 11 48 19](https://user-images.githubusercontent.com/35999196/173028458-4167d9bb-8f98-4e65-b097-0e562928519b.png)

**Comment by kiwanowski** [comment]
Sorry. I didnt design this board. I cant help you
